services:
  - type: web
    name: wealth-backend
    runtime: python
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production

  - type: web
    name: wealth-frontend
    runtime: static
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://wealth-management-e3ke.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
